document.addEventListener('DOMContentLoaded', () => {
    const articles = {
        1: {
            title: "O Novo Rei de Valle surge!",
            content: `
                <p>•》A conversa na cabana continuava, e todas as perguntas acerca do cartaz infelizmente não podiam ser sanadas. O ancião tão pouco sabia sobre quem estava no cartaz, esclarecendo isso para Mix, assim como também não sabia se seria alguém da família Charlotte. Tantas dúvidas e tão poucas respostas, era irritante naquele momento, mas com certeza se os supernovas buscassem por respostas, poderiam encontrar.</p> <br>
                <p>•》E então, saindo juntamente dos piratas, o velho espadachim enfim deixava para trás o seu esconderijo, um lugar que ficou por tantos anos e finalmente poderia se reencontrar  com a luz da esperança que agora brilha sobre Valle. Os três caminhavam discutindo a respeito do passado de Yamato e o que girava em torno da pessoa np cartaz, até darem de cara com o corpo do boi, quase fundindo com a terra pelo largo tempo que ficou ali. Cabia a Mix e Lepaizo se iriam querer dar um enterro ao seu inimigo e inimigo daquela ilha ou deixa-lo ali apodrecendo por toda a eternidade.</p> <br>
                <p>•》Independente da resposta, eles ainda iriam subir para a superfície. E quando chegassem lá, pegariam todos de surpresa, tanto Mix quanto o ancião não eram vistos a muitíssimo tempo. As lágrimas, os abraços e sorriso eram inquestionáveis. Toda a felicidade contagiou aquela ilha que a tanto tempo não sorria. O brilho que emanou por Szchuan agora refletia nas pessoas, e se ele focasse em seus olhos, poderia ver que não eram olhos de medo ou tensão por ser um pirata. Eles estavam apreciando seus heróis de guerra. O seu novo rei. O seu novo Rei Doce.</p> <br>
                <p>•》Mais a frente Lepaizo e Mix percebiam seu companheiro Magnum ao lado de Stalin, e eles sem prestejar corriam para o encontro de seus companheiros. Abraços e várias palavras faziam aquela momento ser mais único. Mais emocionante. Porém não parou apenas em Magnum, ainda chegando, mesmo que atrasada, estava Generosa Farias, e ao seu lado ninguém mais e ninguém menos que Bella. Depois de tantas horas conversando enfim elas haviam chegado a um acordo. Uma era o apoio da outra para tudo, se tornando mais do que apenas companheiras, agora eram como irmãs inseparáveis.</p> <br>
                <p>•》A festa que anteriormente fora interrompida agora continuava, muito mais animada do que antes, tomando a ilha toda com celebrações e desfiles (semelhante ao Carnaval). As árvores e vegetação de Valle ganhavam novas cores das luzes coloridas. Os líderes eram quem comandavam tudo, mas sem deixar de festejar junto dos novos heróis. E eles, eram carregados por tronos nos desfiles, passando por muitas ruas enquanto seriam ovacionados pela população. Todas as tribos se uniam, em um ato histórico para a ilha, por um único motivo: A comemoração e chegada de um novo líder.</p> <br>
                <p>•》Mix era levado até o templo da tribo principal, uma pirâmide estilo Asteca. E quando chegou no topo, fora arrumado no estilo de vestimenta da ilha, com pinturas no corpo todo em tons vermelhos e verde. A cor vermelha simbolizava a vitória, já a verde a esperança. Duas coisas que combinavam com Szchuan. E após a preparação das vestes, uma música começava, com tambores sincronizados e um coral ao fundo, algo que tomou toda a região, ao mesmo tempo que o povo também cantava junto. Ele, Mix, parava a frente no último degrau da escadaria, isso enquanto o próprio ancião, com as mesmas vestes, era levantado por um dos quatro grandes líderes e ele então colocava uma coroa feita inteiramente de uma árvore Adão. Contendo detalhes com as pérolas mais raras de Valle, agora Mix tinha o respeito e à posse da ilha de Valle em suas mãos. O herói do povo, aplaudido de pé. Nas laterais, seus companheiros, todos sendo ovacionados também, Generosa tinha em seu colo um filhote de lobo, aquele pedido para Bella. Já Bella, chorava de emoção, abraçando pela lateral sua irmã.</p> <br>
                <p>•》Assim tinha o fim de uma grande e sangrenta batalha. Com uma vitória suada e sofrida, mas que no fim resultou o que todos esperavam, o que todos queriam desde o começo. Mix e Lepaizo faziam seu nome, e não tardou para as novas recompensas chegarem em suas mãos. Mix havia superados o um bilhão, ele havia se tornado uma potência destrutiva dos sete mares. Sua tripulação enfim dava mais um passo para a glória eterna. Assim a Dominação de Valle, retumbante aos tambores da esperança e liberdade, tinha seu tão esperado fim.</p> <br>
            `
        },
        2: {
            title: "O Asas do Caos",
            content: `
                <p>•》Após a dominação de Valle e tudo que se sucedeu, as novas recompensas eram lançadas ao mar, chegando ao navio da tripulação do Rei Doce. Todos estavam muito animados com os números de vários dígitos sobre suas cabeças, mas uma coisa a mais estava contida no jornal. Nele tinha escrita as seguintes palavras:</p><br>
                <p>~> Após ter vencido um usuário de Haoshoku Haki e usuário de uma akuma no mi poderosa, o imediato dos piratas de Mix Szchuan, o Rei Doce, acabou por receber mérito e reconhecimento do Governo Mundial. Ele, ao lado de seus companheiros conseguiriam encerrar o ciclo de ódio na ilha, tomando conhecimento de seu inimigo e o vencendo de uma vez por todas. Agora, mais do que nunca, essa tripulação tem seu devido lugar no caminho da glória. E como já dito, o imediato Lepaizo ganhou reconhecimento em cima disso, e assim como seu capitão, agora ele é o novo Supernova que Apoo escolheu para a lista. Um novo dia para ser odiado não é mesmo? Senhor Asas do Caos.</p><br>
                <p>•》E com isso é concluído que Valle está na posse dos Reis Doce e Lepaizo consegue seu tão esperado título de Supernova. Qual será o próximo passo deles? Todos estão ansiosos para saber.</p><br>
            `
        },
        3: {
            title: "O Ascender da Kobu Kobu no Mi:  O triunfo de Generosa Farias, A Generosa",
            content: `
            <p>•》Yōkai começava a rir com o desespero da mulher, ele não se importava. Ele ia tirar praticamente tudo daquela maldita tripulação, chegar com o nariz levantado em um lugar desconhecido era imprudente, pouco inteligente. Já Generosa, via sua vida passar diante de seus olhos, ela tinha as piores das visões de todas. O céu escurecia, nem a lua brilhava mais o campo de batalha, tampouco era a esperança presente no ar, o poder da Kobu Kobu no Mi simplesmente parecia ter desaparecido naquele momento, deixando a sua portadora por ela se mostrar fraca naquele momento e aceitar a derrota.</p><br>
            <p>•》O ar estava pesado, os inocentes que ainda estavam no navio viam sua ilha completamente destruída, um clima de tristeza e solidão pairava o ar. Uma criança que via aquela cena começava a chorar loucamente.</p><br>
            <p>- Mamãe... O tio Himejima vai matar aquela moça..? - A mãe estava arrasada, ela não sabia o que responder. Não reconhecia o monstro. - Eu não... Eu não sei, meu amor.</p><br>
            <p>•》Mas algo acontecia, assim que Farias recuperava suas esperanças e simplesmente não estava disposta a aceitar aquilo, ela sentia uma chama ascender dentro dela. De repente, uma onda de poder atingia seu coração, atingia seu corpo, seu cérebro, seus neurônios, sua alma e seu espírito. A dor foi transformada em cura, os ferimentos recentes e mais leves começavam a se regenerar. As lagrimas foi transformada em esperança. A raiva e o ódio foi transformada em amor nos corações de seus companheiros que sentiam seus corpos muito mais fortes. Repentinamente, uma luz começava a envolver a garota, um brilho amarelo, uma aura poderosa era imposta no ar. A criança que chorava de olhos fechados no colo de sua mãe, via um brilho atingir seus olhos, por um momento achou que fosse o sol iniciando o dia, mas a quilômetros de distância Generosa brilhava como uma estrela cadente.            </p><br>
            <p>•》O grito foi forte o suficiente para fazer o coração de Mix bater novamente, o grito foi forte o suficiente para fazer Ares bater de frente com a dor aguda que sentia, o grito foi forte pra fazer Lepaizo se levantar mesmo estando sem uma perna, o grito foi forte o suficiente para um poder muito maior ascender todos os atributos físicos de todos os combatentes dali. O que importava se eles estavam feridos? O que importava de verdade no final das contas? Apenas aceitar a derrota e morrer de uma forma burra para Yōkai? Não. Não com Mhysa (Mãe) ali, presente. Os inocentes que ainda estavam soterrados nos destroços da cidade viam o ascender da mulher e começaram a comemorar, aplaudir.</p><br>
            <p>- NÃO! COMO ISSO É POSSÍVEL!? EU FIZ DE TUDO PRA VOCÊS SEUS INGRATOS! - O poder da Kobu Kobu no Mi dava efeitos negativos em Yōkai, que começava a se sentir mais fraco. Era a chance da tripulação inteira se reerguer. No final das contas todos percebiam que, o triunfo da tripulação não era um supernova com os poderes de controlar doce, ou dois zoans míticas extremamente fortes, ou um dos mink mais forte dos mares, ou até mesmo um insano que controlava facas. Era simplesmente... Farias, era sua essência. Não por conta de seu poder, mas por conta de sua personalidade, a vida ou morte imposta em jogo fazia ela se destacar e ela era a única que conseguia salvar no final das contas. Ela que iria reerguer todos, ela era que seria a luz no fim do túnel, a lâmpada que mais brilhará em uma sala isolada. Yōkai então lançava todos seus tentáculos contra Generosa, quem seria o primeiro sortudo a usufruir dos poderes da Kobu Kobu no Mi despertada? Em seu máximo potencial?</p><br>
            <p></p><br>
            `
        }
    };

    const links = document.querySelectorAll('.jornal-nav ul li a');
    const articleContent = document.getElementById('article-content');

    links.forEach(link => {
        link.addEventListener('click', (event) => {
            event.preventDefault();
            const articleId = event.target.getAttribute('data-article');
            const article = articles[articleId];

            articleContent.innerHTML = `<h2>${article.title}</h2>${article.content}`;
        });
    });
});